### ISSUE TITLE
Duplicated subtype

### ISSUE THREAD

**Issue by Floppy** [theodi/panopticon#116]
If an artefact is tagged as "lunchtime lecture", the tag is lost and it shows twice in the subtype section. This is because the tag string is the same in the subtype and keyword tags.

**Comment by Floppy** [comment]
Also we se this with team.

**Comment by pezholio** [comment]
Urgh. No idea what's going on with this. I think the issue is happening on the gds_content_models side, but I can't get any visibility of what's happening. Should we allow keywords that are the same as categories anyway? Can't see what value it adds.

**Comment by pezholio** [comment]
Yup, genuinely no idea what's going on here.The problem is definitely on the govuk_content_models side - in the Taggable trait here - https://github.com/theodi/govuk_content_models/blob/master/app/traits/taggable.rb 

I have a failing test (which I'll push up to a branch), but I can't see where the problem's happening. Everything's as expected, until I actually save the artefact.

**Comment by pezholio** [comment]
Failing test is in this branch https://github.com/theodi/govuk_content_models/tree/feature-allow-keywords-to-have-the-same-name-as-sections

**Comment by pezholio** [comment]
OK, so the way this ENTIRE thing has been built is it assumes all tag 'ids' are unique. It's not a standard relation, for some reason, taggable models just save an array of tag ids.

So if I have an artefact that is a lunchtime lecture, and I add the tag 'lunchtime lecture' too, the tag ids will be saved as `['lunchtime-lecture', 'lunchtime-lecture']`, so when I try and recover the tags, it'll do a query against ONLY the tag ID, so it'll return the first one it comes across, in this case, the section. This will need a HUGE refactor, which will no doubt uncover all manner of nasties :cry:

**Comment by gilesdring** [comment]
No progress made on this in the period 11-17 June.

**Comment by gilesdring** [comment]
Looking at this, the *quick* way to fix it is to change the event tag from `lunchtime-lecture` to `lunchtime-lecture-event` or `event-lunchtime-lecture` or something else that won't clash. Propose:

1. Changing the seeds file to do this
2. Creating a migration task with the following logic:

    select all artefacts tagged lunchtime-lecture and not tagged lunchtime-lecture-event then apply lunchtime-lecture-event

This avoids overwriting the tags on the future runs.

**Comment by Floppy** [comment]
My only concern is that there might be more. In fact, I'm pretty sure there's at least another one. No problem with doing this, but we should check the others first to see if we need to do some others at the same time.

**Comment by Floppy** [comment]
And we should then add a DB constraint on the tag ID to be unique.

**Comment by gilesdring** [comment]
It's worse than that, Jim...

Propose fixing the event clashes in this round to prove the approach. Others may require a bit more investigation, in case the UI depends on them

<table border=0 cellpadding=0 cellspacing=0 width=595 style='border-collapse:
 collapse;table-layout:fixed;width:595pt'>
 <col width=140 style='mso-width-source:userset;mso-width-alt:5973;width:140pt'>
 <col width=65 span=7 style='width:65pt'>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl65 width=140 style='height:15.0pt;width:140pt'>Tag</td>
  <td class=xl66 width=65 style='width:65pt'>article</td>
  <td class=xl66 width=65 style='width:65pt'>event</td>
  <td class=xl66 width=65 style='width:65pt'>keyword</td>
  <td class=xl66 width=65 style='width:65pt'>organization</td>
  <td class=xl66 width=65 style='width:65pt'>person</td>
  <td class=xl66 width=65 style='width:65pt'>role</td>
  <td class=xl66 width=65 style='width:65pt'>timed_item</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>blog</td>
  <td class=xl68 align=right>1</td>
  <td class=xl68>&nbsp;</td>
  <td class=xl68 align=right>1</td>
  <td class=xl68>&nbsp;</td>
  <td class=xl68>&nbsp;</td>
  <td class=xl68>&nbsp;</td>
  <td class=xl68>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>consultation-response</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>dapaas</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>guide</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>lunchtime-lecture</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>meetup</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>member</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>members</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>odi</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>open-data-challenge-series</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>procurement</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>team</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>trainers</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
 <tr height=15 style='height:15.0pt'>
  <td height=15 class=xl67 style='height:15.0pt;border-top:none'>workshop</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 align=right style='border-top:none'>1</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
  <td class=xl68 style='border-top:none'>&nbsp;</td>
 </tr>
</table>
